# Generated by Django 6.0.5 on 2026-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
